#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=65
STOP=65

USE_PROCD=1
PROG=/sbin/ntp
HOTPLUG_HELPER=/usr/sbin/ntpd.hotplug-helper
NTP_KEYFILE=/var/run/ntpd.keys

config=/var/run/ntpd.conf

trunc() {
	echo -n "" > $config
}

emit() {
	echo -e "$@" >> $config
}

validate_ntp_section() {
	uci_validate_section ntpd timeserver "${1}" \
		'server:list(host)' 'enabled:bool:1' 'enable_server:bool:0' \
		'file_flag:bool:0' 'config_file:string' \
		'broadcast_enabled:bool:0' 'broadcast_key_id:uinteger' 'broadcast:ipaddr' 'ttl:uinteger' 'broadcast_minpoll:uinteger'
}

handle_auth_key() {
	local section="$1"
	local key_id key_type key

	config_get key_id "$section" key_id
	config_get key_type "$section" key_type
	config_get key "$section" key

	echo "$key_id $key_type $key" >> "$NTP_KEYFILE"

	trusted_keys="${trusted_keys:+$trusted_keys }$key_id"
}

handle_ntp_server() {
	local section="$1"
	local key_id host

	config_get host "$section" host
	config_get key_id "$section" key_id

	emit "server $host iburst ${key_id:+key $key_id}"
}

start_service() {
	local server enabled enable_server file_flag config_file intf

	config_load ntpd

	validate_ntp_section ntp || {
		echo "validation failed"
		return 1
	}

	[ "$enabled" = 0 ] && return

	if [ "$file_flag" != 1 ]; then
		trunc
		emit "driftfile /var/lib/ntp/ntp.drift\n"

		if [ "$enable_server" != 0 ]; then
		    emit "restrict default limited kod nomodify notrap nopeer"
		    emit "restrict -6 default limited kod nomodify notrap nopeer"
		else
		    emit "restrict -4 default noserve"
		    emit "restrict -6 default noserve"
		fi
		emit "restrict source noquery"

		emit "\n# No limits for local monitoring"
		emit "restrict 127.0.0.1"
		emit "restrict -6 ::1\n"

		config_foreach handle_ntp_server ntp_server

		[ "$broadcast_enabled" = 1 ] && {
			emit "broadcast $broadcast${ttl:+ ttl $ttl}${broadcast_minpoll:+ minpoll $broadcast_minpoll}${broadcast_key_id:+ key $broadcast_key_id}"
		}

		emit "\n# Authentication"
		emit "keys $NTP_KEYFILE"

		( umask 0066; > "$NTP_KEYFILE" )
		config_foreach handle_auth_key auth_key

		[ -n "$trusted_keys" ] && {
			emit "trustedkey $trusted_keys"
		}
	fi

	if [ -d "/etc/ntpd.d" ]; then
		local entry
		for entry in "/etc/ntpd.d"/*.conf; do
			emit "includefile ${entry}\n"
		done
	fi

	if [ -d "/tmp/ntpd.d" ]; then
		local entry
		for entry in "/tmp/ntpd.d"/*.conf; do
			emit "includefile ${entry}\n"
		done
	fi

	if [ ! -x "$PROG" ]; then
		PROG="/usr/local$PROG"
	fi

	if [ ! -x "$HOTPLUG_HELPER" ]; then
		HOTPLUG_HELPER="/usr/local$HOTPLUG_HELPER"
	fi

	procd_open_instance
	if [ "$file_flag" != 1 ]; then
		procd_set_param command $PROG -g -u ntp:ntp -p /var/run/ntpd.pid -n -c $config
	else
		procd_set_param command $PROG -g -u ntp:ntp -p /var/run/ntpd.pid -n -c $config_file
	fi
	procd_set_param respawn
	procd_close_instance

	which ntpq >/dev/null 2>&1 && {
		procd_open_instance
		procd_set_param command $HOTPLUG_HELPER
		procd_close_instance
	}
}

service_triggers() {
	procd_add_reload_trigger "ntpd"
}

reload_service() {
	stop
	start
}
